language: c
compiler: gcc
dist: xenial

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libgtk-3-dev autopoint build-essential libgtk-3-0 autoconf automake

script:
    - autoreconf -if && ./configure && make && make check && make distcheck